/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const ChannelPartner = IDL.Record({
  'city' : IDL.Text,
  'name' : IDL.Text,
  'company' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
  'mobile' : IDL.Text,
});
export const ContactForm = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
  'mobile' : IDL.Text,
});
export const StudentLead = IDL.Record({
  'city' : IDL.Text,
  'name' : IDL.Text,
  'timestamp' : Time,
  'mobile' : IDL.Text,
  'course' : IDL.Text,
});

export const idlService = IDL.Service({
  'getChannelPartners' : IDL.Func([], [IDL.Vec(ChannelPartner)], []),
  'getContactForms' : IDL.Func([], [IDL.Vec(ContactForm)], []),
  'getStudentLeads' : IDL.Func([], [IDL.Vec(StudentLead)], []),
  'submitChannelPartner' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'submitContactForm' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'submitStudentLead' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const ChannelPartner = IDL.Record({
    'city' : IDL.Text,
    'name' : IDL.Text,
    'company' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
    'mobile' : IDL.Text,
  });
  const ContactForm = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
    'mobile' : IDL.Text,
  });
  const StudentLead = IDL.Record({
    'city' : IDL.Text,
    'name' : IDL.Text,
    'timestamp' : Time,
    'mobile' : IDL.Text,
    'course' : IDL.Text,
  });
  
  return IDL.Service({
    'getChannelPartners' : IDL.Func([], [IDL.Vec(ChannelPartner)], []),
    'getContactForms' : IDL.Func([], [IDL.Vec(ContactForm)], []),
    'getStudentLeads' : IDL.Func([], [IDL.Vec(StudentLead)], []),
    'submitChannelPartner' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'submitContactForm' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'submitStudentLead' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };