/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ChannelPartner {
  'city' : string,
  'name' : string,
  'company' : string,
  'message' : string,
  'timestamp' : Time,
  'mobile' : string,
}
export interface ContactForm {
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
  'mobile' : string,
}
export interface StudentLead {
  'city' : string,
  'name' : string,
  'timestamp' : Time,
  'mobile' : string,
  'course' : string,
}
export type Time = bigint;
export interface _SERVICE {
  'getChannelPartners' : ActorMethod<[], Array<ChannelPartner>>,
  'getContactForms' : ActorMethod<[], Array<ContactForm>>,
  'getStudentLeads' : ActorMethod<[], Array<StudentLead>>,
  'submitChannelPartner' : ActorMethod<
    [string, string, string, string, string],
    undefined
  >,
  'submitContactForm' : ActorMethod<
    [string, string, string, string],
    undefined
  >,
  'submitStudentLead' : ActorMethod<
    [string, string, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];